var editTournamentTpl = _.template([
    '<div class="panel panel-default">',
        '<div class="panel-heading">',
            '<h4> <%= (Name !== "")? "Редактировать турнир": "Создать турнир" %> </h4>',
        '</div>',
        '<div class="panel-body">',
            '<form role="form">',
                '<div class="form-group">',
                    '<label>Название турнира:</label>',
                    '<input name="Name" type="text" class="form-control" value="<%= Name %>" required="required">',
                '</div>',
                '<div class="form-group">',
                    '<label>Описание:</label>',
                    '<textarea name="Description" class="form-control" rows="3">',
                    '<%= Description %>',
                    '</textarea>',
                '</div>',
                '<div class="form-group">',
                    '<label>Сезон:</label>',
                    '<select name="Season" class="form-control">',
                    '<% for (var i = 2009; i < 2024; i++) { %>',
                        '<option <% if (Season === (i + "/" + (i+1))) {',
                                'print("selected");',
                            '} %>>',
                                '<%= i + "/" + (i+1) %>',
                        '</option>',
                    '<% } %>',
                    '</select>',
                '</div>',
                '<div class="form-group">',
                    '<label>Схема:</label>',
                    '<select name="Scheme" class="form-control" required="required">',
                    '<option <% if (Scheme==="1") {print("selected");} %>>1</option>',
                    '<option <% if (Scheme==="2") {print("selected");} %>>2</option>',
                    '<option <% if (Scheme==="2.5") {print("selected");} %>>2.5</option>',
                    '</select>',
                '</div>',
                '<div class="form-group">',
                    '<label>Ссылка на регламент:</label>',
                    '<input name="RegulationsLink" type="text" class="form-control" value="<%= RegulationsLink %>">',
                '</div>',
                '<button type="button" class="btn btn-success save pull-right">',
                    '<i class="glyphicon glyphicon-floppy-saved"></i> Сохранить',
                '</button>',
                '<div class="btn-toolbar pull-left">',
                    '<button type="button" class="btn btn-warning cancel">',
                        '<i class="glyphicon glyphicon-floppy-remove"></i> Отмена',
                    '</button>',
                '</div>',
            '</form>',
        '</div>',
    '</div>'
].join(""));

