var tournamentHomepageTpl = _.template([
    '<div class="panel panel-default">',
        '<div class="panel-heading">',
            '<div class="row">',
                '<div class="col-sm-8">',
                    '<h4>Домашняя страница турнира</h4>',
                '</div>',
                '<div class="col-sm-4">',    
                    '<button class="btn btn-success pull-right edit">',
                        '<i class="glyphicon glyphicon-edit"></i> Редактировать',
                    '</button>',
                '</div>',
            '</div>',
        '</div>',
        '<div class="panel-body">',
            '<ul class="list-group">',
                '<div class="form-group">',
                    '<label>Название турнира:</label>',
                    '<p class="grey"name="Name"><%= Name %></p>',
                '</div>',
                '<div class="form-group">',
                    '<label>Описание:</label>',
                    '<p class="grey" name="Description" style="word-wrap: break-word">',
                    '<%= Description %>',
                    '</p>',
                '</div>',
                '<div class="form-group">',
                    '<label>Сезон:</label>',
                    '<p class="grey" name="Season"><%= Season %></p>',
                '</div>',
                '<div class="form-group">',
                    '<label>Схема:</label>',
                    '<p class="grey" name="Scheme"><%= Scheme %></p>',
                '</div>',
                '<div class="form-group hidden">',
                    '<label>Ссылка на регламент:</label>',
                    '<p class="grey" style="word-wrap: break-word">',
                        '<a name="RegulationsLink" href="<%= RegulationsLink %>"><%= RegulationsLink %></a>',
                    '</p>',
                '</div>',
            '</ul>',                
                '<button type="button" class="btn btn-warning pull-left cancel">',
                    '<i class="glyphicon glyphicon-arrow-left"></i> Назад',
                '</button>',
                '<button type="button" class="btn btn-danger pull-right delete">',
                    '<i class="glyphicon glyphicon-remove"></i> Удалить',
                '</button>',
        '</div>',
    '</div>'
].join(""));