//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolleyManagement.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VolleyManagement.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трансфер должен начинаться до начала турнира.
        /// </summary>
        public static string InvalidPeriodTransfer {
            get {
                return ResourceManager.GetString("InvalidPeriodTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окончание трансферного периода должно быть раньше окончания игр.
        /// </summary>
        public static string InvalidTransferEndpoint {
            get {
                return ResourceManager.GetString("InvalidTransferEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация на турнир должна быть раньше чем его начало.
        /// </summary>
        public static string InvelidPeriodTournament {
            get {
                return ResourceManager.GetString("InvelidPeriodTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете указывать начало периода заявок в прошлом.
        /// </summary>
        public static string LateRegistrationDates {
            get {
                return ResourceManager.GetString("LateRegistrationDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название турнира должно быть уникальным.
        /// </summary>
        public static string TournamentNameMustBeUnique {
            get {
                return ResourceManager.GetString("TournamentNameMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При наличии трансфера необходимо указать дату окончания периода.
        /// </summary>
        public static string TransferEndMissing {
            get {
                return ResourceManager.GetString("TransferEndMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При наличии трансфера необходимо указать дату начала периода.
        /// </summary>
        public static string TransferStartMissing {
            get {
                return ResourceManager.GetString("TransferStartMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя турнира должно быть уникальным.
        /// </summary>
        public static string UniqueNameMessage {
            get {
                return ResourceManager.GetString("UniqueNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email пользователя должен быть уникальным.
        /// </summary>
        public static string UserEmailMustBeUnique {
            get {
                return ResourceManager.GetString("UserEmailMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя и email должны быть уникальны.
        /// </summary>
        public static string UserNameAndEmailMustBeUnique {
            get {
                return ResourceManager.GetString("UserNameAndEmailMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя должно быть уникально.
        /// </summary>
        public static string UserNameMustBeUnique {
            get {
                return ResourceManager.GetString("UserNameMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите телефон правильно.
        /// </summary>
        public static string ValidationCellPhone {
            get {
                return ResourceManager.GetString("ValidationCellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите email правильно.
        /// </summary>
        public static string ValidationEmail {
            get {
                return ResourceManager.GetString("ValidationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите имя правильно.
        /// </summary>
        public static string ValidationFullName {
            get {
                return ResourceManager.GetString("ValidationFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль не может быть пустым.
        /// </summary>
        public static string ValidationPassword {
            get {
                return ResourceManager.GetString("ValidationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите дату рождения верно.
        /// </summary>
        public static string ValidationPlayerBirthYear {
            get {
                return ResourceManager.GetString("ValidationPlayerBirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите имя корректно.
        /// </summary>
        public static string ValidationPlayerFirstName {
            get {
                return ResourceManager.GetString("ValidationPlayerFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите рост корректно.
        /// </summary>
        public static string ValidationPlayerHeight {
            get {
                return ResourceManager.GetString("ValidationPlayerHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите фамилию корректно.
        /// </summary>
        public static string ValidationPlayerLastName {
            get {
                return ResourceManager.GetString("ValidationPlayerLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйта, введите вес корректно.
        /// </summary>
        public static string ValidationPlayerWeight {
            get {
                return ResourceManager.GetString("ValidationPlayerWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, уменьшите текст описания.
        /// </summary>
        public static string ValidationResultDescription {
            get {
                return ResourceManager.GetString("ValidationResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите название турнира.
        /// </summary>
        public static string ValidationResultName {
            get {
                return ResourceManager.GetString("ValidationResultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличен размер email.
        /// </summary>
        public static string ValidationResultRegLink {
            get {
                return ResourceManager.GetString("ValidationResultRegLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите схему корректно.
        /// </summary>
        public static string ValidationResultScheme {
            get {
                return ResourceManager.GetString("ValidationResultScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите данные в поле сезон корректно.
        /// </summary>
        public static string ValidationResultSeason {
            get {
                return ResourceManager.GetString("ValidationResultSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите дату начала сезна корректно.
        /// </summary>
        public static string ValidationTournamentSeason {
            get {
                return ResourceManager.GetString("ValidationTournamentSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите имя пользователя корректно.
        /// </summary>
        public static string ValidationUserName {
            get {
                return ResourceManager.GetString("ValidationUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало периода заявок должно быть раньше чем его окончание.
        /// </summary>
        public static string WrongRegistrationDatesPeriod {
            get {
                return ResourceManager.GetString("WrongRegistrationDatesPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период заявок должен следовать перед началом игр.
        /// </summary>
        public static string WrongRegistrationGames {
            get {
                return ResourceManager.GetString("WrongRegistrationGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальная дата турнира должна следовать перед ее окончанием.
        /// </summary>
        public static string WrongStartTournamentDates {
            get {
                return ResourceManager.GetString("WrongStartTournamentDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало трансфера должно быть после начала турнира.
        /// </summary>
        public static string WrongStartTransferDates {
            get {
                return ResourceManager.GetString("WrongStartTransferDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период регистрации менее чем 3 месяца.
        /// </summary>
        public static string WrongThreeMonthRule {
            get {
                return ResourceManager.GetString("WrongThreeMonthRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало трансферного периода должно быть раньше чем его окончание.
        /// </summary>
        public static string WrongTransferPeriod {
            get {
                return ResourceManager.GetString("WrongTransferPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало трансферного окна должно быть после начала игр.
        /// </summary>
        public static string WrongTransferStart {
            get {
                return ResourceManager.GetString("WrongTransferStart", resourceCulture);
            }
        }
    }
}
