//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolleyManagement.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VolleyManagement.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer has started before tourament.
        /// </summary>
        public static string InvalidPeriodTransfer {
            get {
                return ResourceManager.GetString("InvalidPeriodTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окончание трансферного периода должно быть раньше окончания игр.
        /// </summary>
        public static string InvalidTransferEndpoint {
            get {
                return ResourceManager.GetString("InvalidTransferEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament registration is after of a tournament.
        /// </summary>
        public static string InvelidPeriodTournament {
            get {
                return ResourceManager.GetString("InvelidPeriodTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете указывать начало периода заявок в прошлом.
        /// </summary>
        public static string LateRegistrationDates {
            get {
                return ResourceManager.GetString("LateRegistrationDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the tournament must be unique.
        /// </summary>
        public static string TournamentNameMustBeUnique {
            get {
                return ResourceManager.GetString("TournamentNameMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user email must be unique..
        /// </summary>
        public static string UserEmailMustBeUnique {
            get {
                return ResourceManager.GetString("UserEmailMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name and email must be unique..
        /// </summary>
        public static string UserNameAndEmailMustBeUnique {
            get {
                return ResourceManager.GetString("UserNameAndEmailMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name must be unique..
        /// </summary>
        public static string UserNameMustBeUnique {
            get {
                return ResourceManager.GetString("UserNameMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the telepnone correctly.
        /// </summary>
        public static string ValidationCellPhone {
            get {
                return ResourceManager.GetString("ValidationCellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the email correctly.
        /// </summary>
        public static string ValidationEmail {
            get {
                return ResourceManager.GetString("ValidationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the full name correctly.
        /// </summary>
        public static string ValidationFullName {
            get {
                return ResourceManager.GetString("ValidationFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty!.
        /// </summary>
        public static string ValidationPassword {
            get {
                return ResourceManager.GetString("ValidationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the birth year correctly..
        /// </summary>
        public static string ValidationPlayerBirthYear {
            get {
                return ResourceManager.GetString("ValidationPlayerBirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the first name correctly.
        /// </summary>
        public static string ValidationPlayerFirstName {
            get {
                return ResourceManager.GetString("ValidationPlayerFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the height correctly..
        /// </summary>
        public static string ValidationPlayerHeight {
            get {
                return ResourceManager.GetString("ValidationPlayerHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the last name correctly.
        /// </summary>
        public static string ValidationPlayerLastName {
            get {
                return ResourceManager.GetString("ValidationPlayerLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the weight correctly..
        /// </summary>
        public static string ValidationPlayerWeight {
            get {
                return ResourceManager.GetString("ValidationPlayerWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, reduce the description text.
        /// </summary>
        public static string ValidationResultDescription {
            get {
                return ResourceManager.GetString("ValidationResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the tournament name.
        /// </summary>
        public static string ValidationResultName {
            get {
                return ResourceManager.GetString("ValidationResultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, reduce the link text.
        /// </summary>
        public static string ValidationResultRegLink {
            get {
                return ResourceManager.GetString("ValidationResultRegLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the scheme correctly.
        /// </summary>
        public static string ValidationResultScheme {
            get {
                return ResourceManager.GetString("ValidationResultScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the season correctly.
        /// </summary>
        public static string ValidationResultSeason {
            get {
                return ResourceManager.GetString("ValidationResultSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the season date correctly.
        /// </summary>
        public static string ValidationTournamentSeason {
            get {
                return ResourceManager.GetString("ValidationTournamentSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the user name correctly.
        /// </summary>
        public static string ValidationUserName {
            get {
                return ResourceManager.GetString("ValidationUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало периода заявок должно быть раньше чем его окнчание.
        /// </summary>
        public static string WrongRegistrationDatesPeriod {
            get {
                return ResourceManager.GetString("WrongRegistrationDatesPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период заявок должен следовать перед началом игр.
        /// </summary>
        public static string WrongRegistrationGames {
            get {
                return ResourceManager.GetString("WrongRegistrationGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальная дата турнира должна следовать перед ее окончанием.
        /// </summary>
        public static string WrongStartTournamentDates {
            get {
                return ResourceManager.GetString("WrongStartTournamentDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start transfer date has to be before end date.
        /// </summary>
        public static string WrongStartTransferDates {
            get {
                return ResourceManager.GetString("WrongStartTransferDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало трансферного периода должно быть раньше чем его окнчание.
        /// </summary>
        public static string WrongTransferPeriod {
            get {
                return ResourceManager.GetString("WrongTransferPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало трансферного окна должно быть после начала игр.
        /// </summary>
        public static string WrongTransferStart {
            get {
                return ResourceManager.GetString("WrongTransferStart", resourceCulture);
            }
        }
    }
}
