var editUserTpl = _.template([
    '<div class="panel panel-default">',
        '<div class="panel-heading">',
            '<h4> <%= (UserName !== "")? "Редактирование информации": "Регистрация пользователя" %> </h4>',
        '</div>',
        '<div class="panel-body">',
            '<form role="form">',
                '<div class="form-group">',
                    '<label>Имя:</label>',
                    '<input name="UserName" type="text" class="form-control" value="<%= UserName %>">',
                '</div>',
                '<div class="form-group">',
                    '<label>Фамилия:</label>',
                    '<input name="FullName" type="text" class="form-control" value="<%= FullName %>">',
                '</div>',
                    '<div class="form-group">',
                        '<label>Почта:</label>',
                        '<input name="Email" type="text" class="form-control" value="<%= Email %>">',
                    '</div>',
                '<div class="form-group">',
                    '<label>Пароль:</label>',
                    '<input name="Password" type="password" class="form-control" value="<%= Password %>">',
                '</div>',
                
                '<div class="form-group">',
                    '<label>Мобильный телефон:</label>',
                    '<input name="CellPhone" type="text" class="form-control" value="<%= CellPhone %>">',
                '</div>',
                '<button type="button" class="btn btn-success save pull-right">',
                    '<i class="glyphicon glyphicon-floppy-saved"></i> Сохранить',
                '</button>',
                '<div class="btn-toolbar pull-left">',
                    '<button type="button" class="btn btn-warning cancel">',
                        '<i class="glyphicon glyphicon-floppy-remove"></i> Отмена',
                    '</button>',
                '</div>',
            '</form>',
        '</div>',
    '</div>'
].join(''));