var userHomepageTpl = _.template([
    '<div class="panel panel-default">',
        '<div class="panel-heading">',
            '<div class="row">',
                '<div class="col-sm-8">',
                    '<h4>Информация пользователя</h4>',
                '</div>',
                '<div class="col-sm-4">',    
                    '<button class="btn btn-success pull-right edit">',
                        '<i class="glyphicon glyphicon-edit"></i> Редактировать',
                    '</button>',
                '</div>',
            '</div>',        
        '</div>',
        
        
            '<div class="panel-body user-panel">',
                '<div class="row">',
                    '<div class="col-md-9 user-info-container">',
                        '<div class="form-group">',
                            '<label>Имя:</label></span>',
                            '<p class="grey" name="UserName"><%= UserName %></p>',
                        '</div>',
                        '<div class="form-group">',
                            '<label>Фамилия:</label>',
                            '<p class="grey" name="FullName"><%= FullName %></p>',
                        '</div>',
                        '<div class="form-group">',
                            '<label>Почта:</label>',
                            '<p class="grey" name="Email"><%= Email %></p>',
                        '</div>',
                        '<div class="form-group">',
                            '<label>Мобильный телефон:</label>',
                            '<p class="grey" name="CellPhone"><%= CellPhone %></p>',
                        '</div>', 
                    '</div>',
                    '<div class="col-md-3 user-logo-container">',
                        '<i class="glyphicon glyphicon-user img-circle"></i>',
                    '</div>',
                '</div>',
                '<div class="row">',
                    '<div class="col-md-12 user-info-container">',
                        '<button type="button" class="btn btn-warning pull-left cancel">',
                            '<i class="glyphicon glyphicon-arrow-left"></i> Назад',
                        '</button>',
                        '<button type="button" class="btn btn-danger pull-right delete">',
                            '<i class="glyphicon glyphicon-remove"></i> Удалить',
                        '</button>',
                    '</div>',
                '</div>',
            '</div>',
        

    '</div>'
].join(""));