//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolleyManagement.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VolleyManagement.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gmail message is invalid..
        /// </summary>
        internal static string ArgumentExceptionInvalidGmailMessage {
            get {
                return ResourceManager.GetString("ArgumentExceptionInvalidGmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gmail address is invalid..
        /// </summary>
        internal static string ArgumentNullExceptionInvalidGmailAddress {
            get {
                return ResourceManager.GetString("ArgumentNullExceptionInvalidGmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gmail password is invalid..
        /// </summary>
        internal static string ArgumentNullExceptionInvalidGmailPassword {
            get {
                return ResourceManager.GetString("ArgumentNullExceptionInvalidGmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thank you for your feedback!.
        /// </summary>
        internal static string FeedbackConfirmationLetterBody {
            get {
                return ResourceManager.GetString("FeedbackConfirmationLetterBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User notification.
        /// </summary>
        internal static string FeedbackConfirmationLetterSubject {
            get {
                return ResourceManager.GetString("FeedbackConfirmationLetterSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feedback №{0}, 
        ///Date: {1}.
        ///User email: {2},
        ///Status: {3}
        ///Content: {4}.
        /// </summary>
        internal static string FeedbackEmailBodyToAdmins {
            get {
                return ResourceManager.GetString("FeedbackEmailBodyToAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feedback №{0}.
        /// </summary>
        internal static string FeedbackEmailSubjectToAdmins {
            get {
                return ResourceManager.GetString("FeedbackEmailSubjectToAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GoogleEmailAddress.
        /// </summary>
        internal static string GmailAddress {
            get {
                return ResourceManager.GetString("GmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EmailMessage.
        /// </summary>
        internal static string GmailMessage {
            get {
                return ResourceManager.GetString("GmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GoogleEmailPassword.
        /// </summary>
        internal static string GmailPassword {
            get {
                return ResourceManager.GetString("GmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your apply was confirmed!.
        /// </summary>
        internal static string TournamentRequestConfirmitionLetterBody {
            get {
                return ResourceManager.GetString("TournamentRequestConfirmitionLetterBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tournament Request №{0}, 
        ///User: {1}.
        ///Tournament: {2},
        ///Team: {3}.
        /// </summary>
        internal static string TournamentRequestEmailBodyToAdmins {
            get {
                return ResourceManager.GetString("TournamentRequestEmailBodyToAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tournament Request №{0}.
        /// </summary>
        internal static string TournamentRequestEmailSubjectToAdmins {
            get {
                return ResourceManager.GetString("TournamentRequestEmailSubjectToAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User notification.
        /// </summary>
        internal static string TournamentRequestLetterSubject {
            get {
                return ResourceManager.GetString("TournamentRequestLetterSubject", resourceCulture);
            }
        }
    }
}
