//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolleyManagement.UI.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GameReportViews {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameReportViews() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VolleyManagement.UI.App_GlobalResources.GameReportViews", typeof(GameReportViews).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to tournament details.
        /// </summary>
        public static string BackToTournament {
            get {
                return ResourceManager.GetString("BackToTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balls ia a game.
        /// </summary>
        public static string BallsGroupHeader {
            get {
                return ResourceManager.GetString("BallsGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost.
        /// </summary>
        public static string BallsLostHeader {
            get {
                return ResourceManager.GetString("BallsLostHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        public static string BallsRatioHeader {
            get {
                return ResourceManager.GetString("BallsRatioHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won.
        /// </summary>
        public static string BallsWonHeader {
            get {
                return ResourceManager.GetString("BallsWonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string GamesGroupHeader {
            get {
                return ResourceManager.GetString("GamesGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost.
        /// </summary>
        public static string GamesLostHeader {
            get {
                return ResourceManager.GetString("GamesLostHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string GamesTotalHeader {
            get {
                return ResourceManager.GetString("GamesTotalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0:3.
        /// </summary>
        public static string GamesWithScoreNilThreeHeader {
            get {
                return ResourceManager.GetString("GamesWithScoreNilThreeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1:3.
        /// </summary>
        public static string GamesWithScoreOneThreeHeader {
            get {
                return ResourceManager.GetString("GamesWithScoreOneThreeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3:0.
        /// </summary>
        public static string GamesWithScoreThreeNilHeader {
            get {
                return ResourceManager.GetString("GamesWithScoreThreeNilHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3:1.
        /// </summary>
        public static string GamesWithScoreThreeOneHeader {
            get {
                return ResourceManager.GetString("GamesWithScoreThreeOneHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3:2.
        /// </summary>
        public static string GamesWithScoreThreeTwoHeader {
            get {
                return ResourceManager.GetString("GamesWithScoreThreeTwoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2:3.
        /// </summary>
        public static string GamesWithScoreTwoThreeHeader {
            get {
                return ResourceManager.GetString("GamesWithScoreTwoThreeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won.
        /// </summary>
        public static string GamesWonHeader {
            get {
                return ResourceManager.GetString("GamesWonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As of {0:dd.MM.yyyy}.
        /// </summary>
        public static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no complete games for today.
        /// </summary>
        public static string NoGameResults {
            get {
                return ResourceManager.GetString("NoGameResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string PointsHeader {
            get {
                return ResourceManager.GetString("PointsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string PositionHeader {
            get {
                return ResourceManager.GetString("PositionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets.
        /// </summary>
        public static string SetsGroupHeader {
            get {
                return ResourceManager.GetString("SetsGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost.
        /// </summary>
        public static string SetsLostHeader {
            get {
                return ResourceManager.GetString("SetsLostHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        public static string SetsRatioHeader {
            get {
                return ResourceManager.GetString("SetsRatioHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won.
        /// </summary>
        public static string SetsWonHeader {
            get {
                return ResourceManager.GetString("SetsWonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string TeamHeader {
            get {
                return ResourceManager.GetString("TeamHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament &quot;{0}&quot;.
        /// </summary>
        public static string TournamentStandingsLegend {
            get {
                return ResourceManager.GetString("TournamentStandingsLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament table.
        /// </summary>
        public static string TournamentStandingsTitle {
            get {
                return ResourceManager.GetString("TournamentStandingsTitle", resourceCulture);
            }
        }
    }
}
