//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolleyManagement.UI.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlayerViews {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlayerViews() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VolleyManagement.UI.App_GlobalResources.PlayerViews", typeof(PlayerViews).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add player to team.
        /// </summary>
        public static string AddPlayerToTeam {
            get {
                return ResourceManager.GetString("AddPlayerToTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply for tournament.
        /// </summary>
        public static string ApplyForTournament {
            get {
                return ResourceManager.GetString("ApplyForTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Apply team for .
        /// </summary>
        public static string ApplyTeamFor {
            get {
                return ResourceManager.GetString("ApplyTeamFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to previous page.
        /// </summary>
        public static string BackPrevPage {
            get {
                return ResourceManager.GetString("BackPrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a player.
        /// </summary>
        public static string ChoosingPlayer {
            get {
                return ResourceManager.GetString("ChoosingPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose players.
        /// </summary>
        public static string ChoosingPlayers {
            get {
                return ResourceManager.GetString("ChoosingPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new player.
        /// </summary>
        public static string CreateNewPlayer {
            get {
                return ResourceManager.GetString("CreateNewPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new player.
        /// </summary>
        public static string CreatePlayerTitle {
            get {
                return ResourceManager.GetString("CreatePlayerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete him?.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete player.
        /// </summary>
        public static string DeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting player.
        /// </summary>
        public static string DeletePlayerTitle {
            get {
                return ResourceManager.GetString("DeletePlayerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing player.
        /// </summary>
        public static string EditPlayerTitle {
            get {
                return ResourceManager.GetString("EditPlayerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  I accept .
        /// </summary>
        public static string IAccept {
            get {
                return ResourceManager.GetString("IAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players with this name was not found.
        /// </summary>
        public static string NotFoundPlayerMessage {
            get {
                return ResourceManager.GetString("NotFoundPlayerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of the player.
        /// </summary>
        public static string PlayerDetailsTitle {
            get {
                return ResourceManager.GetString("PlayerDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string PlayerLegend {
            get {
                return ResourceManager.GetString("PlayerLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string PlayersIndexTitle {
            get {
                return ResourceManager.GetString("PlayersIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player was not found because he was removed. Editing operation is impossible. To create a player use the link..
        /// </summary>
        public static string PlayerWasDeleted {
            get {
                return ResourceManager.GetString("PlayerWasDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to search.
        /// </summary>
        public static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  tournament.
        /// </summary>
        public static string Tournament {
            get {
                return ResourceManager.GetString("Tournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  tournament regulations..
        /// </summary>
        public static string TournamentRegulations {
            get {
                return ResourceManager.GetString("TournamentRegulations", resourceCulture);
            }
        }
    }
}
