//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TournamentViews {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TournamentViews() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VolleyManagement.UI.App_GlobalResources.TournamentViews", typeof(TournamentViews).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add division.
        /// </summary>
        public static string AddDivision {
            get {
                return ResourceManager.GetString("AddDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add game result.
        /// </summary>
        public static string AddGameResult {
            get {
                return ResourceManager.GetString("AddGameResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add group.
        /// </summary>
        public static string AddGroup {
            get {
                return ResourceManager.GetString("AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications to Tournaments.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply For Tournament.
        /// </summary>
        public static string ApplyForTournament {
            get {
                return ResourceManager.GetString("ApplyForTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team 2.
        /// </summary>
        public static string AwayTeamPlaceholder {
            get {
                return ResourceManager.GetString("AwayTeamPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze match.
        /// </summary>
        public static string BronzeGameName {
            get {
                return ResourceManager.GetString("BronzeGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new tournament.
        /// </summary>
        public static string CreateNewTournament {
            get {
                return ResourceManager.GetString("CreateNewTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create one more.
        /// </summary>
        public static string CreateOneMore {
            get {
                return ResourceManager.GetString("CreateOneMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new tournament.
        /// </summary>
        public static string CreateTournamentTitle {
            get {
                return ResourceManager.GetString("CreateTournamentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string CurrentTournamentsHeader {
            get {
                return ResourceManager.GetString("CurrentTournamentsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this team?.
        /// </summary>
        public static string DeleteTournamentTeamConfirm {
            get {
                return ResourceManager.GetString("DeleteTournamentTeamConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting tournament.
        /// </summary>
        public static string DeleteTournamentTitle {
            get {
                return ResourceManager.GetString("DeleteTournamentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit scheduled game.
        /// </summary>
        public static string EditScheduledGameTitle {
            get {
                return ResourceManager.GetString("EditScheduledGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing tournament.
        /// </summary>
        public static string EditTournamentTitle {
            get {
                return ResourceManager.GetString("EditTournamentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final match.
        /// </summary>
        public static string FinalGameName {
            get {
                return ResourceManager.GetString("FinalGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show finished.
        /// </summary>
        public static string FinishedTournaments {
            get {
                return ResourceManager.GetString("FinishedTournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string FinishedTournamentsHeader {
            get {
                return ResourceManager.GetString("FinishedTournamentsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free day.
        /// </summary>
        public static string FreeDay {
            get {
                return ResourceManager.GetString("FreeDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game was not found in the tournament.
        /// </summary>
        public static string GameNotFoundInTournament {
            get {
                return ResourceManager.GetString("GameNotFoundInTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team 1.
        /// </summary>
        public static string HomeTeamPlaceholder {
            get {
                return ResourceManager.GetString("HomeTeamPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Teams.
        /// </summary>
        public static string ManageTeams {
            get {
                return ResourceManager.GetString("ManageTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Application.
        /// </summary>
        public static string NoApplication {
            get {
                return ResourceManager.GetString("NoApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No games were scheduled yet.
        /// </summary>
        public static string NoGamesScheduled {
            get {
                return ResourceManager.GetString("NoGamesScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No teams available in the tournament.
        /// </summary>
        public static string NoTeamsAvailable {
            get {
                return ResourceManager.GetString("NoTeamsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying period.
        /// </summary>
        public static string RegistrationFieldsTitle {
            get {
                return ResourceManager.GetString("RegistrationFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule game.
        /// </summary>
        public static string ScheduleGame {
            get {
                return ResourceManager.GetString("ScheduleGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string ScheduleGameLegend {
            get {
                return ResourceManager.GetString("ScheduleGameLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule game.
        /// </summary>
        public static string ScheduleGameTitle {
            get {
                return ResourceManager.GetString("ScheduleGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule for.
        /// </summary>
        public static string ScheduleTitle {
            get {
                return ResourceManager.GetString("ScheduleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show game results.
        /// </summary>
        public static string ShowGameResults {
            get {
                return ResourceManager.GetString("ShowGameResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tournament table.
        /// </summary>
        public static string ShowTournamentStandings {
            get {
                return ResourceManager.GetString("ShowTournamentStandings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day off.
        /// </summary>
        public static string TeamDayOff {
            get {
                return ResourceManager.GetString("TeamDayOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament details.
        /// </summary>
        public static string TournamentDetailsTitle {
            get {
                return ResourceManager.GetString("TournamentDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No division is selected.
        /// </summary>
        public static string TournamentDivisionIsNotSelected {
            get {
                return ResourceManager.GetString("TournamentDivisionIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament.
        /// </summary>
        public static string TournamentFieldsTitle {
            get {
                return ResourceManager.GetString("TournamentFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No group is selected.
        /// </summary>
        public static string TournamentGroupIsNotSelected {
            get {
                return ResourceManager.GetString("TournamentGroupIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament.
        /// </summary>
        public static string TournamentLegend {
            get {
                return ResourceManager.GetString("TournamentLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournaments.
        /// </summary>
        public static string TournamentsIndexTitle {
            get {
                return ResourceManager.GetString("TournamentsIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No team is selected.
        /// </summary>
        public static string TournamentTeamIsNotSelected {
            get {
                return ResourceManager.GetString("TournamentTeamIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer period.
        /// </summary>
        public static string TransferFieldsTitle {
            get {
                return ResourceManager.GetString("TransferFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        public static string UpcomingTournamentsHeader {
            get {
                return ResourceManager.GetString("UpcomingTournamentsHeader", resourceCulture);
            }
        }
    }
}
