//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolleyManagement.UI.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VolleyManagement.UI.App_GlobalResources.ViewModelResources", typeof(ViewModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixMe: Confirm password.
        /// </summary>
        public static string ConfirmUserPassword {
            get {
                return ResourceManager.GetString("ConfirmUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} должно быть заполнено в диапазоне {1} - {2}.
        /// </summary>
        public static string FieldRange {
            get {
                return ResourceManager.GetString("FieldRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; является обязательным..
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} должно содержать только печатаемые символы.
        /// </summary>
        public static string InvalidEntriesError {
            get {
                return ResourceManager.GetString("InvalidEntriesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный идентификатор турнира.
        /// </summary>
        public static string InvalidTournamentId {
            get {
                return ResourceManager.GetString("InvalidTournamentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; не может содержать более &quot;{1}&quot; символов.
        /// </summary>
        public static string MaxLengthErrorMessage {
            get {
                return ResourceManager.GetString("MaxLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; должно быть в диапазоне &quot;{1}&quot; - &quot;{2}&quot;.
        /// </summary>
        public static string NotInRange {
            get {
                return ResourceManager.GetString("NotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixMe: Password didn&apos;t match.
        /// </summary>
        public static string PasswordDidNotMatch {
            get {
                return ResourceManager.GetString("PasswordDidNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указан неверный год рождения.
        /// </summary>
        public static string PlayerBirthFieldRange {
            get {
                return ResourceManager.GetString("PlayerBirthFieldRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год рождения.
        /// </summary>
        public static string PlayerBirthYear {
            get {
                return ResourceManager.GetString("PlayerBirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string PlayerFirstName {
            get {
                return ResourceManager.GetString("PlayerFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} должно содержать только буквы.
        /// </summary>
        public static string PlayerFirstNameInvalidEntriesError {
            get {
                return ResourceManager.GetString("PlayerFirstNameInvalidEntriesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не может быть пустым.
        /// </summary>
        public static string PlayerFirstNameRequired {
            get {
                return ResourceManager.GetString("PlayerFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рост.
        /// </summary>
        public static string PlayerHeight {
            get {
                return ResourceManager.GetString("PlayerHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указан неверный рост.
        /// </summary>
        public static string PlayerHeightFieldRange {
            get {
                return ResourceManager.GetString("PlayerHeightFieldRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string PlayerLastName {
            get {
                return ResourceManager.GetString("PlayerLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} должна содержать только буквы.
        /// </summary>
        public static string PlayerLastNameInvalidEntriesError {
            get {
                return ResourceManager.GetString("PlayerLastNameInvalidEntriesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не может быть пустой.
        /// </summary>
        public static string PlayerLastNameRequired {
            get {
                return ResourceManager.GetString("PlayerLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не может содержать более {1} символов.
        /// </summary>
        public static string PlayerMaxLengthErrorMessage {
            get {
                return ResourceManager.GetString("PlayerMaxLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вес.
        /// </summary>
        public static string PlayerWeight {
            get {
                return ResourceManager.GetString("PlayerWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указан неверный вес.
        /// </summary>
        public static string PlayerWeightFieldRange {
            get {
                return ResourceManager.GetString("PlayerWeightFieldRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string TournamentDescription {
            get {
                return ResourceManager.GetString("TournamentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название турнира.
        /// </summary>
        public static string TournamentName {
            get {
                return ResourceManager.GetString("TournamentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка на регламент.
        /// </summary>
        public static string TournamentRegulationsLink {
            get {
                return ResourceManager.GetString("TournamentRegulationsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Схема.
        /// </summary>
        public static string TournamentScheme {
            get {
                return ResourceManager.GetString("TournamentScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сезон.
        /// </summary>
        public static string TournamentSeason {
            get {
                return ResourceManager.GetString("TournamentSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string UserCellPhone {
            get {
                return ResourceManager.GetString("UserCellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string UserDescription {
            get {
                return ResourceManager.GetString("UserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string UserFullName {
            get {
                return ResourceManager.GetString("UserFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
    }
}
