//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolleyManagement.UI.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VolleyManagement.UI.App_GlobalResources.ViewModelResources", typeof(ViewModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The applying period should be at least 3 months.
        /// </summary>
        public static string ApplyingDateThreeMonth {
            get {
                return ResourceManager.GetString("ApplyingDateThreeMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tournament should start after the applying period end.
        /// </summary>
        public static string ApplyingPeriodBeforeGamesStart {
            get {
                return ResourceManager.GetString("ApplyingPeriodBeforeGamesStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of the applying period.
        /// </summary>
        public static string ApplyingPeriodEnd {
            get {
                return ResourceManager.GetString("ApplyingPeriodEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of the applying period.
        /// </summary>
        public static string ApplyingPeriodStart {
            get {
                return ResourceManager.GetString("ApplyingPeriodStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of the applying period must be earlier than its end.
        /// </summary>
        public static string ApplyingStartBeforeEnd {
            get {
                return ResourceManager.GetString("ApplyingStartBeforeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of the applying period must be later than today.
        /// </summary>
        public static string ApplyingStartBeforeNow {
            get {
                return ResourceManager.GetString("ApplyingStartBeforeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixMe: Confirm password.
        /// </summary>
        public static string ConfirmUserPassword {
            get {
                return ResourceManager.GetString("ConfirmUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string DivisionDefaultName {
            get {
                return ResourceManager.GetString("DivisionDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Name.
        /// </summary>
        public static string DivisionName {
            get {
                return ResourceManager.GetString("DivisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not contain more than {1} symbols.
        /// </summary>
        public static string DivisionNameMaxLengthErrorMessage {
            get {
                return ResourceManager.GetString("DivisionNameMaxLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be empty.
        /// </summary>
        public static string DivisionNameRequired {
            get {
                return ResourceManager.GetString("DivisionNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisions.
        /// </summary>
        public static string Divisions {
            get {
                return ResourceManager.GetString("Divisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of the tournament must be later than its start.
        /// </summary>
        public static string EndGamesBeforeStart {
            get {
                return ResourceManager.GetString("EndGamesBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; must be in a range {1} - {2}.
        /// </summary>
        public static string FieldRange {
            get {
                return ResourceManager.GetString("FieldRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; is required.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date of the tournament.
        /// </summary>
        public static string GamesEnd {
            get {
                return ResourceManager.GetString("GamesEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date of the tournament.
        /// </summary>
        public static string GamesStart {
            get {
                return ResourceManager.GetString("GamesStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string GroupDefaultName {
            get {
                return ResourceManager.GetString("GroupDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not contain more than {1} symbols.
        /// </summary>
        public static string GroupNameMaxLengthErrorMessage {
            get {
                return ResourceManager.GetString("GroupNameMaxLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be empty.
        /// </summary>
        public static string GroupNameRequired {
            get {
                return ResourceManager.GetString("GroupNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} must contain only printable characters.
        /// </summary>
        public static string InvalidEntriesError {
            get {
                return ResourceManager.GetString("InvalidEntriesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tournament id.
        /// </summary>
        public static string InvalidTournamentId {
            get {
                return ResourceManager.GetString("InvalidTournamentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login providers.
        /// </summary>
        public static string LoginProviders {
            get {
                return ResourceManager.GetString("LoginProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; can not contain more than {1} symbols.
        /// </summary>
        public static string MaxLengthErrorMessage {
            get {
                return ResourceManager.GetString("MaxLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; must be in a range {1} - {2}.
        /// </summary>
        public static string NotInRange {
            get {
                return ResourceManager.GetString("NotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixMe: Password didn&apos;t match.
        /// </summary>
        public static string PasswordDidNotMatch {
            get {
                return ResourceManager.GetString("PasswordDidNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date of birth.
        /// </summary>
        public static string PlayerBirthFieldRange {
            get {
                return ResourceManager.GetString("PlayerBirthFieldRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string PlayerBirthYear {
            get {
                return ResourceManager.GetString("PlayerBirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PlayerFirstName {
            get {
                return ResourceManager.GetString("PlayerFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should contain only letters and spaces, or &quot; - &quot;, &quot; &apos; &quot; characters (no more than one consecutive). {0} must not end with a special character..
        /// </summary>
        public static string PlayerFirstNameInvalidEntriesError {
            get {
                return ResourceManager.GetString("PlayerFirstNameInvalidEntriesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be empty.
        /// </summary>
        public static string PlayerFirstNameRequired {
            get {
                return ResourceManager.GetString("PlayerFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string PlayerFullName {
            get {
                return ResourceManager.GetString("PlayerFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string PlayerHeight {
            get {
                return ResourceManager.GetString("PlayerHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid height.
        /// </summary>
        public static string PlayerHeightFieldRange {
            get {
                return ResourceManager.GetString("PlayerHeightFieldRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string PlayerLastName {
            get {
                return ResourceManager.GetString("PlayerLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should contain only letters and spaces, or &quot; - &quot;, &quot; &apos; &quot; characters (no more than one consecutive). {0} must not end with a special character..
        /// </summary>
        public static string PlayerLastNameInvalidEntriesError {
            get {
                return ResourceManager.GetString("PlayerLastNameInvalidEntriesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be empty.
        /// </summary>
        public static string PlayerLastNameRequired {
            get {
                return ResourceManager.GetString("PlayerLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not contain more than {1} symbols.
        /// </summary>
        public static string PlayerMaxLengthErrorMessage {
            get {
                return ResourceManager.GetString("PlayerMaxLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player was deleted successfully.
        /// </summary>
        public static string PlayerWasDeletedSuccessfully {
            get {
                return ResourceManager.GetString("PlayerWasDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string PlayerWeight {
            get {
                return ResourceManager.GetString("PlayerWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid weight.
        /// </summary>
        public static string PlayerWeightFieldRange {
            get {
                return ResourceManager.GetString("PlayerWeightFieldRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        public static string TeamAchievements {
            get {
                return ResourceManager.GetString("TeamAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        public static string TeamCaptain {
            get {
                return ResourceManager.GetString("TeamCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team captain is required.
        /// </summary>
        public static string TeamCaptainRequired {
            get {
                return ResourceManager.GetString("TeamCaptainRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coach.
        /// </summary>
        public static string TeamCoach {
            get {
                return ResourceManager.GetString("TeamCoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not contain more than {1} symbols.
        /// </summary>
        public static string TeamMaxLengthErrorMessage {
            get {
                return ResourceManager.GetString("TeamMaxLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be empty.
        /// </summary>
        public static string TeamNameRequired {
            get {
                return ResourceManager.GetString("TeamNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roster.
        /// </summary>
        public static string TeamRoster {
            get {
                return ResourceManager.GetString("TeamRoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TournamentDescription {
            get {
                return ResourceManager.GetString("TournamentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament name.
        /// </summary>
        public static string TournamentName {
            get {
                return ResourceManager.GetString("TournamentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament regulations link.
        /// </summary>
        public static string TournamentRegulationsLink {
            get {
                return ResourceManager.GetString("TournamentRegulationsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme.
        /// </summary>
        public static string TournamentScheme {
            get {
                return ResourceManager.GetString("TournamentScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string TournamentSeason {
            get {
                return ResourceManager.GetString("TournamentSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date of the transfer window.
        /// </summary>
        public static string TransferEnd {
            get {
                return ResourceManager.GetString("TransferEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of the transfer must be earlier than its end.
        /// </summary>
        public static string TransferEndAfterStart {
            get {
                return ResourceManager.GetString("TransferEndAfterStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of the transfer period must be earlier than the tournament end.
        /// </summary>
        public static string TransferEndBeforeGamesEnd {
            get {
                return ResourceManager.GetString("TransferEndBeforeGamesEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date of the transfer window.
        /// </summary>
        public static string TransferStart {
            get {
                return ResourceManager.GetString("TransferStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of the transfer period should be within the tournament.
        /// </summary>
        public static string TransferStartBeforeGamesStart {
            get {
                return ResourceManager.GetString("TransferStartBeforeGamesStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tournament name should be unique.
        /// </summary>
        public static string UniqueNameMessage {
            get {
                return ResourceManager.GetString("UniqueNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string UserCellPhone {
            get {
                return ResourceManager.GetString("UserCellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string UserDescription {
            get {
                return ResourceManager.GetString("UserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string UserFullName {
            get {
                return ResourceManager.GetString("UserFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
    }
}
